In [ ]:
# Introduction to NumPy

# NumPy: the functions for creating arrays, multi-dimensional arrays, randomly generated arrays, element-wise operations, comparison operations and summarizing operations.

In [1]:
import numpy as np

In [2]:
# Creating arrays

# The simplest function for creating arrays is zeros. It takes one argument - the size of the array - and creates an array of that size filled with zeros:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# There is a similar function, ones, which fills the array with ones instead:

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# And if you want to fill an array with some arbitrary number, use full: first you specify the size of the array, then the element to fill it with:

np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
# If you have a Python list and want to create an array from it, use the array function and pass the list as the argument:
a = np.array([1, 2, 3, 5, 7, 12])
a

# To access an element of the array, use its index. Remember that indexing in Python starts with zero, so to access the element 3 we use index 2:

a[2]


# And we can use the assignment operator to change it - say, replace 3 with 10:

a[2] = 10
a


array([ 1,  2, 10,  5,  7, 12])

In [10]:
# Two more useful functions for creating arrays. arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. The last element is exclusive:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# linspace creates an array of a given size filled with numbers evenly spaced between the first and the second parameter

# from the result below, we can see that:The first element is 0, the last is 100, and everything in between is filled in. With 11 elements the steps are nice round numbers - 0, 10, 20, and so on.

np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
# Multi-dimensional arrays

# So far we created one-dimensional arrays. NumPy can also create two-dimensional and multi-dimensional arrays.

# We use the same zeros function, but now we specify the dimensions of the array: the first number is the number of rows, the second is the number of columns:

np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# We can also create a two-dimensional array from a list of lists:
n =  np.array([
    [1, 2, 4],
    [4, 5, 6],
    [6, 7, 8]
])
n

array([[1, 2, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
# Accessing elements works the same as with one-dimensional arrays, except we now have two indices - rows and columns are both indexed from zero. To access the element in row 0, column 1:
n[0, 1]

np.int64(2)

In [18]:
# And again we can use the assignment operator - replace that 2 with 20:
n[0, 1] = 20
n

array([[ 1, 20,  4],
       [ 4,  5,  6],
       [ 6,  7,  8]])

In [19]:
# If we pass only one index, we get an entire row:
n[2]

array([6, 7, 8])

In [21]:
# We can rewrite the entire row too - the only condition is that the dimensions match. Let's make the last row all ones:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  4],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [22]:
# The same works for columns. To get a column we need to specify only the second index, but we cannot leave the first one empty - we put the colon operator there, meaning "all the rows":
n[:, 1]

array([20,  5,  1])

In [23]:
# And we can assign to the column as well:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [ ]:
# Randomly generated arrays

# NumPy can also generate arrays with random numbers. Let's generate a two-dimensional array with 5 rows and 2 columns:



# This gives us an array with random numbers between 0 and 1, sampled from the standard uniform distribution. Every time we execute this cell, we get different numbers.
np.random.rand(5, 2)

array([[0.80067362, 0.18156257],
       [0.77441509, 0.30972391],
       [0.05373399, 0.73529649],
       [0.65385232, 0.10557164],
       [0.65979094, 0.28239831]])

In [30]:
# If we want to make the results reproducible - so that when you run this code you get the same numbers as I do - we can fix the random seed. These numbers are not really random, they are pseudorandom: they are generated by an algorithm (umPy uses a classic algorithm called the Mersenne Twister (MT19937).), and we can set the seed of this generator. Then the sequence of numbers produced on my computer and on your computer will be the same:

# How MT19937 works: It works by taking a massive state of 624 integers. Every time you ask for a number, it applies a series of bitwise math operations (shifting bits left/right, and combining them using AND, OR, and XOR logic gates) to "twist" those integers and extract a massive 32-bit integer.

np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [ ]:
# 1. What is the Mean?The mean (\[\mu \] for a population, \[\={x}\] for a sample) is the arithmetic average of a dataset. It represents the central balance point of your data. How it's calculated: You add up all the values in a dataset and divide by the total number of values.In a Normal Distribution: The mean sits exactly in the center at the highest peak of the bell curve. It determines where the entire curve is positioned along the horizontal axis.

# 2. What is Standard Deviation?The standard deviation (\[\sigma \] for a population, \[s\] for a sample) measures the spread or dispersion of data points around the mean. It tells you how tightly packed or widely scattered your data is. Low Standard Deviation: The data points are clustered closely around the mean. This creates a tall, narrow bell curve.High Standard Deviation: The data points are spread out far from the mean. This creates a short, wide, and flat bell curve.
# A standard normal distribution is a special type of normal distribution that has a mean of 0 and a standard deviation of 1

In [32]:
# There are many different distributions we can sample from. To draw numbers from the standard normal distribution, we add an n to the name - randn stands for "random normal":
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [34]:
# And for random integers there is randint, where we specify the lowest number, the highest number (exclusive - so this gives values between 0 and 99) and the size:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [35]:
# Element-wise operations

# first we create an array
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
#  to add a number to all elements of this array? With NumPy we can just write:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
# If it was a usual Python list, we wouldn't be able to do this - we would need to write a loop and add the number to each element. NumPy makes it easier: + 1 adds one to each element. The same works for multiplication - every element gets multiplied by 2:
a * 2

array([0, 2, 4, 6, 8])

In [ ]:
# Array Operations

# Numpy excels in performing mathematical operations on arrays efficiently.

In [39]:
# Element-wise Operations

# You can perform operations on entire arrays element by element:
# This is exactly what we did when we multiplied the random array by 100. And of course we can also divide, subtract, and do everything else we want. We can even chain operations:

b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [38]:
# Comparison operations

# Comparison operations are also element-wise. Let's check which elements of a are greater than or equal to 2:
a >= 2

array([False, False,  True,  True,  True])

In [40]:
# The first element is less than 2, the second is less than 2, but 2 is greater than or equal to 2 - and the same is true for the rest.

# We can also compare two arrays element by element - which elements of a are greater than the corresponding elements of b:
a > b

array([False, False,  True,  True,  True])

In [41]:
# Summarizing operations

# Element-wise operations return another array. There is a different kind of operation that instead returns a single number - I call them summarizing operations.
# For example, min returns the smallest number:

a.min()

np.int64(0)

In [42]:
# max returns the maximal number, sum computes the sum of all elements (0 + 1 + 2 + 3 + 4 = 10), and mean computes the average:

a.sum()
a.mean()

np.float64(2.0)

In [43]:
# Here is also Standard deviation, 
a.std()

np.float64(1.4142135623730951)