In [1]:
import numpy as np

In [2]:
# Creating arrays

# The simplest function for creating arrays is zeros. It takes one argument - the size of the array - and creates an array of that size filled with zeros:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# There is a similar function, ones, which fills the array with ones instead:

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# And if you want to fill an array with some arbitrary number, use full: first you specify the size of the array, then the element to fill it with:

np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
# If you have a Python list and want to create an array from it, use the array function and pass the list as the argument:
a = np.array([1, 2, 3, 5, 7, 12])
a

# To access an element of the array, use its index. Remember that indexing in Python starts with zero, so to access the element 3 we use index 2:

a[2]


# And we can use the assignment operator to change it - say, replace 3 with 10:

a[2] = 10
a


array([ 1,  2, 10,  5,  7, 12])

In [10]:
# Two more useful functions for creating arrays. arange creates a range of numbers - it works like the Python function range, except instead of an iterator it gives us a NumPy array. The last element is exclusive:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# linspace creates an array of a given size filled with numbers evenly spaced between the first and the second parameter

# from the result below, we can see that:The first element is 0, the last is 100, and everything in between is filled in. With 11 elements the steps are nice round numbers - 0, 10, 20, and so on.

np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
# Multi-dimensional arrays

# So far we created one-dimensional arrays. NumPy can also create two-dimensional and multi-dimensional arrays.

# We use the same zeros function, but now we specify the dimensions of the array: the first number is the number of rows, the second is the number of columns:

np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])